steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: 
  - -c
  - |
    if [ -n "${_DEPLOYMENT}" ]; then
      gcloud secrets versions access latest --secret=metaform-ui-${_DEPLOYMENT}-env --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env
    fi
- name: 'node'
  entrypoint: 'bash'
  env:
    - "DEBIAN_FRONTEND=noninteractive"
    - "AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}"
    - "AWS_DEFAULT_REGION=${_AWS_DEFAULT_REGION}"
  args:
  - -c
  - |
    npm install
    npm run build
    if [ -n "${_DEPLOYMENT}" ]; then
      apt update && apt install -y unzip &&
      curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" &&
      unzip awscli-bundle.zip &&
      ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws &&
      /usr/local/bin/aws  --version &&
      /usr/local/bin/aws s3 cp --recursive ./build s3://${_S3_BUCKET} --acl public-read &&
      /usr/local/bin/aws cloudfront create-invalidation --distribution-id ${_CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
    fi