steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir ~/.aws/ \
    echo "[default]" >> ~/.aws/credentials \
    echo "aws_access_key_id = ${}" >> ~/.aws/credentials \
    echo "aws_secret_access_key = ${_AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
